version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  schema-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/schema-registry
    volumes:
      - .:/usr/src/app
    extra_hosts:
      - "registry.agsiri.com:10.0.0.11"  # For macOS

volumes:
  mongo-data:

